routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login'); 
});

Route::get('/download/{id}', 'MyFileController@pdfgenerate')->name('download');

/*Route::resource('doctors','DoctorController');*/

Route::resource('appointment', 'AppointmentController');
Route::resource('doctors', 'DoctorController'); 
Route::resource('my-files', 'MyFileController');

Route::resource('chat', 'ChatController'); 
Route::resource('video-call', 'VideoCallController'); 
Route::resource('my-account', 'MyAccountController'); 


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/pages/appointment.blade.php
@extends('admin.master')

@section('title') 
    Home || Dashboard
@endsection
 
@section('main-content')
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Appointments</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Create Appointment</button></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Doctor Name</th>
                <th>Date</th>
                <th>Time</th>
                <th>Cancel</th>
                <th>Chat</th>
                <th>Video</th>
              </tr>

            </thead>
            <tbody>
              @foreach($appointments as $appointment)
              <tr>
                <td>{{ $appointment->appointment }}</td>
                <td>{{ $appointment->date }}</td>
                <td>{{ $appointment->time }}</td>
                <td>
                  <form id="delete-form-{{$appointment->id}}" action="{{route('appointment.destroy',$appointment->id)}}" method="post" style="display:none;">
                                                @csrf
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="if(confirm('Are you sure, You want to delete this?'))
                                            {
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{$appointment->id}}').submit();
                                            }else{
                                                event.preventDefault();
                                                    }" class="btn btn-danger">
                  <i class="fa fa-times"></i></a></td>
                <td><a href="{{ route('chatify') }}" class="btn btn-success"><i class="fa fa-comments"></i></a></td>
                <td><a href="" class="btn btn-danger"><i class="fa fa-video"></i></a></td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
<!-- Modal -->
<div class="modal fade" id="exampleModal"  tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form action="" method="POST">
           {{ csrf_field() }}
  <div class="form-group">   
    <input type="date" class="form-control" name="date">
  </div>
  <div class="form-group">
    <select name="appointment" class="form-control">
      @foreach( $doctors as $doctor )
      <option value="{{ $doctor->doctor_name}}">{{ $doctor->doctor_name }}</option>
      @endforeach

    </select>
  </div>
    <div class="form-group">
    <input type="time" class="form-control" name="time">
  </div>
  <button type="submit" class="btn btn-primary float-sm-right">Save</button>
</form>
      </div>
    </div>
  </div>
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/pages/chat.blade.php
 @extends('admin.master')

@section('title')
    Chat || Dashboard
@endsection

@section('main-content') 
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Chat</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Blank Page</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Title</h3> 

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
          Start creating your amazing application!
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div> 
@endsection

resources/views/admin/pages/doctors.blade.php
@extends('admin.master')

@section('title')
    My Files || Dashboard
@endsection

@section('main-content')  
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Doctors</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Add Doctors</button></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr class="bg-primary">
                <th>Doctor Name</th>
                <th>Email</th>
                <th>Specialization</th>
                <th>Action</th>
              </tr>

            </thead>
            <tbody>
              @foreach($doctors as $doctor)
              <tr>
                <td>{{ $doctor->doctor_name }}</td>
                <td>{{ $doctor->email }}</td>
                <td>{{ $doctor->specialization }}</td>
                <td>
                  <a href="" class="btn btn-success"><i class="fa fa-edit"></i></a> 
                  <form id="delete-form-{{$doctor->id}}" action="{{route('doctors.destroy',$doctor->id)}}" method="post" style="display:none;">
                                                @csrf
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="if(confirm('Are you sure, You want to delete this?'))
                                            {
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{$doctor->id}}').submit();
                                            }else{
                                                event.preventDefault();
                                                    }" class="btn btn-danger">
                  <i class="fa fa-trash"></i></a>
                </td> 
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
<!-- Modal -->
<div class="modal fade" id="exampleModal"  tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form action="" method="POST">
          {{ csrf_field() }}
        <div class="form-group">   
          <input type="text" class="form-control" name="doctor_name" placeholder="Doctor Name">
        </div>
        <div class="form-group">   
          <input type="email" class="form-control" name="email" placeholder="Email">
        </div>
        <div class="form-group">   
          <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        <div class="form-group">   
          <input type="text" class="form-control" name="specialization" placeholder="Specialization">
        </div>
        <button type="submit" class="btn btn-primary float-sm-right">Save</button>
      </form>
      </div>
    </div>
  </div>
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/pages/my-account.blade.php
 @extends('admin.master')

@section('title')
    My Account || Dashboard
@endsection

@section('main-content') 
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>My Account</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button>
          </div>
        </div>
        <div class="card-body">
          <table class="table">
            <tbody>
              <tr>
                <th scope="row">Name</th>
                <td>{{ Auth::user()->name }}</td>
                <td rowspan="4"><img src="https://www.flaticon.com/svg/static/icons/svg/21/21104.svg" width="250" height="250"></td>
                
              </tr>
              <tr>
                <th scope="row">Role</th>
                <td>{{ Auth::user()->roles }}</td>
              </tr>
              <tr>
                <th scope="row">Email</th>
                <td>{{ Auth::user()->email }}</td>
              </tr>
              <tr>
                <th scope="row">Password</th>
                <td>{{ Auth::user()->password }}</td>
              </tr>
              <tr>
                <th scope="row">Phone</th>
                <td>{{ Auth::user()->phone }}</td>
                <td rowspan="2" class="text-center">
                  <a href="" class="btn btn-success" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-edit"></i>&nbsp;Update</a>
                </td>
              </tr>
              <tr>
                <th scope="row">Address</th>
                <td>{{ Auth::user()->address }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

      <!-- Modal -->
      <div class="modal fade" id="exampleModal"  tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              <form action="{{ route('my-account.update', Auth::user()->id) }}" method="POST">
                @csrf
                {{method_field('PATCH')}}
              <div class="form-group">    
                <input type="text" class="form-control" name="name" value="{{ Auth::user()->name }}" placeholder="Name">
                <input type="hidden" class="form-control" name="id" value="{{ Auth::user()->id }}"> 
              </div>
              <div class="form-group">   
                <input type="email" class="form-control" name="email" value="{{ Auth::user()->email }}" placeholder="Email" readonly>
              </div>
              <div class="form-group">   
                <input type="text" class="form-control" name="roles" value="{{ Auth::user()->roles }}" placeholder="Roles" readonly>
              </div>
              <div class="form-group">   
                <input type="password" class="form-control" name="password" value="{{ Auth::user()->password }}" placeholder="Password">
              </div>
              <div class="form-group">   
                <input type="text" class="form-control" name="phone" value="{{ Auth::user()->phone }}" placeholder="Phone">
              </div>
              <div class="form-group">    
                <input type="text" class="form-control" name="address" value="{{ Auth::user()->address }}" placeholder="Address">
              </div>
              
              <button type="submit" class="btn btn-primary float-sm-right">Update</button>
            </form>
            </div>
          </div>
        </div>
      </div>

    </section>
    <!-- /.content -->
  </div> 
@endsection

resources/views/admin/pages/my-files.blade.php
@extends('admin.master')

@section('title')
    My Files || Dashboard
@endsection

@section('main-content') 
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>File Uploads</h1>
          </div>
            @if(Auth::user()->roles == 'admin' || Auth::user()->roles == 'patient')
          <div class="col-sm-6">
            <!-- <form action="" method="post">
              {{ csrf_field() }} -->
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item">
                
                  <div class="form-group">
                    <input type="file" class="form-control-file" name="file_name">
                  </div>
              </li>&nbsp; -->
              <li><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModal">upload</button></li>
            </ol>
            <!-- </form> -->
          </div> 
          @endif
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-body">
         <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Sender</th>
                <th>Download</th>
                <th>Delete</th>
              </tr>

            </thead>
            <tbody>
              @foreach($myfiles as $myfile)
              <tr>
                <!-- <td>{{ $myfile->image }}</td>   -->
                <td><img src="{{ asset($myfile->image) }}" alt="" width="50px" height="40px"></td>  
                <td>{{ $myfile->email }}</td>
                <td><a href="{{ route('download',['id'=>$myfile->id]) }}" class="btn btn-primary"><i class="fa fa-download"></i></a></td> 
                <td> 
                  <form id="delete-form-{{$myfile->id}}" action="{{route('my-files.destroy',$myfile->id)}}" method="post" style="display:none;">
                                                @csrf
                                                {{method_field('DELETE')}}

                                            </form>
                                            <a href="" onclick="if(confirm('Are you sure, You want to delete this?'))
                                            {
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{$myfile->id}}').submit();
                                            }else{
                                                event.preventDefault();
                                                    }" class="btn btn-danger">
                  <i class="fa fa-trash"></i></a>
                </td>                
              </tr> 
              @endforeach
            </tbody>
          </table>
          <section class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                @if(Auth::user()->roles =='admin' || Auth::user()->roles =='doctor')
                <div class="col-sm-6">
                   <div class="form-group row">
                    <h3 class="col-sm-3">Send File</h3>
                      <div class="col-sm-3">
                        <select class="form-control">
                           <option value="">Select</option> 
                           @foreach($myfiles as $myfile)                  
                           <option value="{{$myfile->email}}, {{$myfile->file_name}}">{{$myfile->email}},{{$myfile->file_name}}</option> 
                           @endforeach                  
                      </select>
                      </div>
                    </div> 
                
              </div>
              <div class="col-sm-6">
                  <!-- <form action="" method="post">
                    {{ csrf_field() }} -->
                  <ol class="breadcrumb float-sm-right">
                    <!-- <li class="breadcrumb-item">
                      
                        <div class="form-group">
                          <input type="file" class="form-control-file" name="file_name">
                        </div>
                    </li>&nbsp; -->
                    <li><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModal">upload</button></li>
                  </ol>
                  <!-- </form> -->
                </div>

                @endif
              </div>
            </div>
          </section>
        </div>
        <!-- /.card-body -->
        
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

      <!-- Modal -->
<div class="modal fade" id="exampleModal"  tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {{ csrf_field() }}
        <div class="form-group">   
          <input type="text" class="form-control" name="name" placeholder="Name" value="{{Auth::user()->name}}" readonly>
        </div>
        <div class="form-group">   
          <input type="email" class="form-control" name="email" placeholder="Email" value="{{Auth::user()->email}}" readonly>
        </div>
        <div class="form-group">   
          <input type="file" class="form-control-file" name="image">
        </div>
        <button type="submit" class="btn btn-primary float-sm-right">Save</button>
      </form>
      </div>
    </div>
  </div>
</div>

    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/admin/pages/video-call.blade.php
 @extends('admin.master')

@section('title')
    Video Call || Dashboard
@endsection

@section('main-content') 
  	 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Video Call</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Video Call</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Make Video Call</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button>
          </div>
        </div>
        <div class="card-body text-center">
          <!-- <a href="#" class="btn btn-danger" style="font-size: 50px;"><i class="fa fa-video"></i></a> -->
          <video id="vidDisplay" autoplay="true">
            
          </video> 
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div> 

  <script type="text/javascript">
    var video = document.querySelector("#vidDisplay");
    
    if (navigator.mediaDevices.getUserMedia) {
  navigator.mediaDevices.getUserMedia({ video: true })
    .then(function (stream) {
      video.srcObject = stream;
    })
    .catch(function (err0r) {
      console.log("Something went wrong!");
    });
}
  </script>
@endsection